name: Arch Linux 臺灣社群
name_en: Arch Linux Taiwan Community
url: https://archlinux.tw
markdown: redcarpet
highlighter: 'pygments'
timezone: 'Asia/Taipei'
exclude: ['Gemfile', 'Gemfile.lock', 'AUTHORS', 'LICENSE', 'NOTICE', 'README.md', 'CHRONICLES.md', 'config.rb', 'build.sh']
keep_files: ['bootstrap']
rss_post_limit: 10
paginate: 5
paginate_path: "news/page:num"
